### ISSUE TITLE
ecryptfs breaks saving/loading circuits

### ISSUE THREAD

**Issue by BFH-ktt1** [flathub/com.github.reds.LogisimEvolution#5]
Currently the application is only allowed to store/load from the "Documents" folder. When the home-directory is encrypted by ecryptfs following problems are encountered:
1) Saving and loading circuits from the home directory is possible during a current session, closing logisim will "erase" these circuits.
2) It is impossible to change to the "Documents" directory, hence there is no possibility to store the created circuits in a non-volatile method when ecryptfs is used.

In case the home-directory is not encrypted by ecryptfs this problem does not ocure.
I did not look into the details, but mark it for the moment as bug.

**Comment by TheEvilSkeleton** [comment]
I'm guessing it's likely due to it *only* having access to the `~/Documents` directory. When you run `flatpak run --filesystem=home com.github.reds.LogisimEvolution`, can you save from anywhere in your home directory without logisim-evolution erasing the file?

Also, I think the "erase" part is an upstream issue. It should error out and notify the user that the file has not/cannot be saved.
