### ISSUE TITLE
none-volatile and volatile storage

### ISSUE THREAD

**Issue by BFH-ktt1** [flathub/com.github.reds.LogisimEvolution#6]
Probably related to #5 :
When saving logisim circuits in the home-directory, they will disappear after closing logisim, one has to save them in the "Dokuments" folder. This is not documented, and no warning is given. This issue is related to the sandbox-environment of flatpak and not to the application.
I mark it as documentation for the moment

**Comment by TheEvilSkeleton** [comment]
I'm guessing it's likely due to it *only* having access to the `~/Documents` directory. When you run `flatpak run --filesystem=home com.github.reds.LogisimEvolution`, can you save to anywhere in your home directory without logisim-evolution erasing the file?

Also, I think the "erase" part is an upstream issue. It should error out and notify the user that the file has not/cannot be saved.

**Comment by TheEvilSkeleton** [comment]
When you run `flatpak run --filesystem=home com.github.reds.LogisimEvolution`, can you save to anywhere in your home directory without logisim-evolution erasing the file?

Also, I think the "erase" part is an upstream issue. It should error out and notify the user that the file has not/cannot be saved.

**Comment by BFH-ktt1** [comment]
@TheEvilSkeleton , running it as you sugessted (so with --filesystem=home) solves both this issue and issue #5. I think that it makes sense to allow for the complete home-directory and not only restrict to the Documents folder.
